### ISSUE TITLE
composer.json is invalid

### ISSUE THREAD

**Issue by daim2k5** [sandermangel/ffm-adminpermissions#1]
See https://getcomposer.org/doc/04-schema.md for details on the schema
Name "Ffm/Adminpermissions" does not match the best practice (e.g. lower-cased/with-dashes). We suggest using "ffm/adminpermissions" instead. As such you will not be able to submit it to Packagist.
require.magento-hackathon/magento-composer-installer : unbound version constraints (*) should be avoided

**Comment by sandermangel** [comment]
Thanks for the details. Checked a couple of modules on the Firegento github but most had version "*". Could you make a suggestion for what would be the best thing to do here? 

Name was updated

**Comment by daim2k5** [comment]
Suggest instead of require for modules.
Example : https://github.com/firegento/firegento-logger/blob/master/composer.json

**Comment by sandermangel** [comment]
So, should be ok now. Please let me know if anything is missing!
https://github.com/sandermangel/ffm-adminpermissions/blob/master/composer.json

**Comment by daim2k5** [comment]
:+1: perfect.
